% import fit parameters
years = 2009:2018;
params = readtable('../data/params.csv', 'ReadRowNames', true);
params = params(string(years),:);

% settings
linewidth = 1.2;
colors = readmatrix('colors.csv');
colors = colors([1,3,4,8,10,13,15:end],:);
myxlim = [0.1, 10e6/params.T(1)*2];
myylim = [1e-12, 250];
markers = 'os^dh>';
legendX = 130;
legendY = 125;
legendspacing = 0.7;
shiftfactor = 0.45;
fontsize = 12;


% --------------------------------
% import cdf
cdfs = containers.Map('KeyType','double','ValueType','any');
for year = years
    filename = sprintf('../data/irs%d.csv', year);
    cdfs(year) = importcdf(filename);
end

% plot first year at the top, 2018 at the bottom
figure('Position', [400,40,430,750])
toprightaxes = axes('Position', [0.123 0.08 0.75 0.85],...
    'XAxisLocation', 'top',...
    'YAxisLocation', 'right',...
    'LabelFontSizeMultiplier', 1,...
    'FontSize', fontsize,...
    'DefaultTextFontSize', fontsize,...
    'YScale', 'log',...
    'XScale', 'log',...
    'XLim', myxlim*params('2018',:).T/1000,...
    'YLim', myylim,...
    'YTick', 10.^(-11:2),...
    'YTickLabel', [repmat("",1,9),"0.01%","0.1%","1%","10%","100%"],...
    'XTick', [10 100 1000 10000],....
    'XTickLabel', ["10", "100", "1,000", "10,000"]);
xlabel('Adjusted gross income in the USA in 2018 (k$)')
botleftaxes = axes('Position', get(gca, 'Position'),...
    'XAxisLocation', 'bottom',...
    'YAxisLocation', 'left',...
    'Color', 'none',...
    'LabelFontSizeMultiplier', 1,...
    'FontSize', fontsize,...
    'DefaultTextFontSize', fontsize,...
    'YScale', 'log',...
    'XScale', 'log',...
    'XLim', myxlim,...
    'YLim', myylim,...
    'YTick',10.^(-11:2),...
    'YTickLabel', [repmat("",1,9),"0.01%","0.1%","1%","10%","100%"],...
    'XTick', [0.1 1 10 100],....
    'XTickLabel', ["0.1", "1", "10", "100"]);
xlabel('Rescaled adjusted gross income,')
% do r/T separately
text(151.7, 1.33e-13, '$$\frac{r}{T}$$', 'Interpreter', 'latex')
% do ylabel manually
text(0.05, 7e-9,'Cumulative percent of returns',...
    'Rotation', 90, 'Color', [0.15 0.15 0.15])
hold on

for year = years
    i = year - years(1) + 1;
    color = colors(mod(i-1,length(colors))+1, :);
    marker = markers(mod(i-1,length(markers))+1);
    shift = 10^(-i+1); % shift down from max of 100

    % calculate fit curve with points evenly-spaced in log-log
    r = exp(linspace(0, log(10e6), 1000));
    fitcurve = interpcdf(params.T(i),...
        params.alphai(i),...
        params.r0(i),...
        r);
    
    % plot interpolated fit, intersecting fit if it's the last year, and
    % then the data points
    plot(r/params.T(i),...
        fitcurve*100*shift,...
        'Color', color,...
        'LineWidth', linewidth)
    
    plot(cdfs(year).r/params.T(i),...
        cdfs(year).frac_returns*100*shift,...
        marker,...
        'Color', color,...
        'LineWidth', linewidth)
    
    if year == years(end)
        % exponential fit line
        X = 0.02:0.01:5.5;
        plot(X, exp(-X)*100*shift,...
            'Color', 'k',...
            'LineWidth', linewidth);
        
        % pareto fit line
        X = 0.5*params.rstar(end):1e3:10e6;
        plot(X/params.T(end),...
            params.paretocoeff(i)*X.^(-params.alpha(i))*100*shift,...
            'Color', 'k',...
            'LineWidth', linewidth)
        
        % intersection point
        plot(params.rstar(end)/params.T(end),...
            params.fp(end)*100*shift,...
            'ko',...
            'MarkerFaceColor', 'k',...
            'MarkerSize', 3)
    end
    
    fp_r0 = interpcdf(...
            params.T(i),...
            params.alphai(i),...
            params.r0(i),...
            params.r0(i));
    plot(params.r0(i)/params.T(i),...
        fp_r0*100*shift,...
        'rp',...
        'LineWidth', linewidth,...
        'MarkerFaceColor', 'r')
end


%% intersection annotations
% horizontal fp line for 2018
fp = params.fp(end);
rstar_norm = params.rstar(end)/params.T(end);
plot([myxlim(1), rstar_norm],...
    [fp, fp]*100*shift,...
    'Color', 'k',...
    'LineStyle', '--',...
    'LineWidth', linewidth)
% do variable and value separately because I hate my life
text(0.2, 2e-9,...
    '$$f_p$$',...
    'Color', 'k',...
    'Interpreter', 'latex',...
    'FontSize', 1.1*fontsize)
text(0.28, 2.4e-9,...
    ' = 4.1%',...
    'Color', 'k',...
    'FontWeight', 'default')

% vertical r* line for 2018
line([rstar_norm, rstar_norm],...
    [myylim(1), fp*100*shift],...
    'Color', 'k',...
    'LineStyle', '--',...
    'LineWidth', linewidth)
text(4.1, 3.6e-12,...
    '$$\frac{r_*}{T}$$',...
    'Color', 'k',...
    'Interpreter', 'latex')
text(6.29, 3.9e-12,...
    sprintf(' = %0.1f', rstar_norm),...
    'Color', 'k',...
    'FontWeight', 'default')

% vertical r0 line for 2018
r0_norm = params.r0(end)/params.T(end);
line([r0_norm, r0_norm],...
    [myylim(1), fp_r0*100*shift],...
    'Color', 'r',...
    'LineStyle', '-',...
    'LineWidth', linewidth)
text(0.47, 3.6e-12,...
    '$$\frac{r_0}{T}$$',...
    'Color', 'r',...
    'Interpreter', 'latex')
text(0.76, 3.9e-12,...
    sprintf(' = %0.1f', r0_norm),...
    'Color', 'r',...
    'FontWeight', 'default')


%% legend
% matlab legend function leaves unnecessary space between markers and labels
% so the legend needs to be done manually
for year = years
   % need to shift year labels down by the same amount each iteration, which
   % means we need to multiply by a constant factor < 1 since the yscale is log
   i = year - years(1) + 1;
   color = colors(mod(i-1,length(colors))+1,:);
   marker = markers(mod(i-1,length(markers))+1);
  
   text(legendX,legendY*shiftfactor^(i-1),...
       num2str(year),'Color',color, 'FontWeight','Bold')
   plot(legendspacing*legendX, legendY*shiftfactor^(i-1),...
       'o','Color',color, 'Marker', marker, 'MarkerSize',6,...
       'LineWidth', linewidth)
   
end
% add the red star for r0/T to the left of the legend
text(17.2, 24.2,'$$\frac{r_0}{T}$$',...
    'Color','r',...
    'Interpreter', 'latex')
plot(0.1*legendX, legendY*shiftfactor^2,...
    'o','Color','r', 'Marker', 'p', 'MarkerSize',6,...
    'LineWidth', linewidth, 'MarkerFaceColor', 'r')

%% saving figure so that it isn't just 8.5" x 11"
% get the Position in inches, not pixels
set(gcf, 'Units', 'Inches');
figpos = get(gcf, 'Position');
% PaperSize is automatically [8.5, 11]
set(gcf, 'PaperSize', figpos(3:4));
saveas(gcf, 'fig2.pdf');