% settings
allparams = readtable('../data/params.csv', 'ReadRowNames', true);
years1 = 1983:1992;
params1 =  allparams(string(years1),:);
years2 = 1993:1999;
params2 =  allparams(string(years2),:);
years3 = 2000:2018;
params3 = allparams(string(years3),:);
years4 =  2009:2018;
params4 = allparams(string(years4),:);

markersize = 2.5;
linewidth = 1.2;
fontsize = 12;
leftylim = [2.7 6];
rightylim = [0.8 1.85];
thisxlim = [1981 2019];
legendbox = 'off';

figure('Position',[350,75,600,550])
% next make axes for r0/T and r*/T
leftaxes = axes(...
    'XLim', thisxlim,...
    'XMinorTick', 'on',...
    'YMinorTick', 'on',...
    'YLim', leftylim,...
    'LabelFontSizeMultiplier', 1,...
    'FontSize', fontsize,...
    'DefaultTextFontSize', fontsize);
xlabel('Year')
% leave room for latex formatting in ylabel
ylabel('Crossover income levels           and         ')
text(1977.7, 4.62, '$$r_*/T$$',...
    'Color', 'b',...
    'Interpreter', 'latex',...
    'FontSize', 1.1*fontsize,...
    'Rotation', 90)
text(1977.7, 5.17, '$$r_0/T$$',...
    'Color', 'k',...
    'Interpreter', 'latex',...
    'FontSize', 1.1*fontsize,...
    'Rotation', 90)
hold on

% 5 sections for r*/T plots, just 1 section for r0/T
plot(years1, params1.rstar ./ params1.T,...
    'b-o',...
    'MarkerFaceColor', 'b',...
    'MarkerSize', markersize,...
    'LineWidth', linewidth)
plot([1992 1993],...
    allparams(["1992" "1993"],:).rstar ./ allparams(["1992" "1993"],:).T,...
    'b:',...
    'LineWidth', linewidth)
plot(years2, params2.rstar ./ params2.T,...
    'b-o',...
    'MarkerFaceColor', 'b',...
    'MarkerSize', markersize,...
    'LineWidth', linewidth)
plot([1999 2000],...
    allparams(["1999" "2000"],:).rstar ./ allparams(["1999" "2000"],:).T,...
    'b:',...
    'LineWidth', linewidth)
plot(years3, params3.rstar ./ params3.T,...
    'b-o',...
    'MarkerFaceColor', 'b',...
    'MarkerSize', markersize,...
    'LineWidth', linewidth)

plot(years4, params4.r0 ./ params4.T,...
    'k-o',...
    'MarkerFaceColor', 'k',...
    'MarkerSize', markersize,...
    'LineWidth', linewidth)

% add latex variables in manually
legend(["Crossover in piecewise fit,   " "" "" "" "",...
    "Crossover in interpolated fit,   "],...
    'Location', 'southwest',...
    'Box', legendbox)
text(1999.7, 3, '$$r_*/T$$',...
    'Color', 'b',...
    'Interpreter', 'latex',...
    'FontSize', 1.1*fontsize)
text(2000.7, 2.85, '$$r_0/T$$',...
    'Color', 'k',...
    'Interpreter', 'latex',...
    'FontSize', 1.1*fontsize)


% first make axes that go with alpha on the right
rightaxes = axes(...
    'Position', get(leftaxes, 'Position'),...
    'Color', 'none',...
    'XLim', thisxlim,...
    'XMinorTick', 'on',...
    'YLim', rightylim,...
    'YAxisLocation', 'right',...
    'XAxisLocation', 'top',...
    'XTickLabel', [],...
    'LabelFontSizeMultiplier', 1,...
    'FontSize', fontsize,...
    'DefaultTextFontSize', fontsize);
ylabel('Pareto exponents     and      ')
text(2022.6, 1.395, '$$\alpha$$',...
    'Color', 'm',...
    'Interpreter', 'latex',...
    'FontSize', 1.1*fontsize,...
    'Rotation', 90)
text(2022.6, 1.51, '$$\alpha_i$$',...
    'Color', 'r',...
    'Interpreter', 'latex',...
    'FontSize', 1.1*fontsize,...
    'Rotation', 90)
hold on

% 5 sections for alpha simple plot, just 1 for alphai
plot(years1, params1.alpha,...
    'm-o',...
    'MarkerFaceColor', 'm',...
    'MarkerSize', markersize,...
    'LineWidth', linewidth)
plot([1992 1993],...
    allparams(["1992" "1993"],:).alpha,...
    'm:',...
    'LineWidth', linewidth)
plot(years2, params2.alpha,...
    'm-o',...
    'MarkerFaceColor', 'm',...
    'MarkerSize', markersize,...
    'LineWidth', linewidth)
plot([1999 2000],...
    allparams(["1999" "2000"],:).alpha,...
    'm:',...
    'LineWidth', linewidth)
plot(years3, params3.alpha,...
    'm-o',...
    'MarkerFaceColor', 'm',...
    'MarkerSize', markersize,...
    'LineWidth', linewidth)

plot(years4, params4.alphai,...
    'r-o',...
    'MarkerFaceColor', 'r',...
    'MarkerSize', markersize,...
    'LineWidth', linewidth)
% do variables in latex separately
legend(["Pareto exponent in tail fit," "" "" "" "",...
    "Pareto exponent in interpolated fit,"],...
    'Location', [.39,0.83,0.45,0.07],...
    'Box', legendbox)
ylabel('Pareto exponents     and      ')
text(2011, 1.789, '$$\alpha$$',...
    'Color', 'm',...
    'Interpreter', 'latex',...
    'FontSize', 1.1*fontsize)
text(2015.6, 1.747, '$$\alpha_i$$',...
    'Color', 'r',...
    'Interpreter', 'latex',...
    'FontSize', 1.1*fontsize)


% arrows
annotation('arrow', [0.76 0.86], [0.66 0.66],...
    'Color', 'm',...
    'LineWidth', linewidth)
annotation('arrow', [0.76 0.86], [0.4 0.4],...
    'Color', 'r',...
    'LineWidth', linewidth)
annotation('arrow', [0.31 0.21], [0.39 0.39],...
    'Color', 'b',...
    'LineWidth', linewidth)
annotation('arrow', [0.67 0.57], [0.23 0.23],...
    'Color', 'k',...
    'LineWidth', linewidth)

%% saving figure so that it isn't just 8.5" x 11"
% get the Position in inches, not pixels
set(gcf, 'Units', 'Inches');
figpos = get(gcf, 'Position');
% PaperSize is automatically [8.5, 11]
set(gcf, 'PaperSize', figpos(3:4));
saveas(gcf, 'fig4.pdf');

