% import tax Lorenz data
taxlorenz1983 = importtaxlorenz('../data/irs1983.csv');
taxlorenz2018 = importtaxlorenz('../data/irs2018.csv');
% interpolate data with PCHIP
interp1983 = griddedInterpolant(taxlorenz1983.frac_returns,...
    taxlorenz1983.frac_tax, 'pchip');
interp2018 = griddedInterpolant(taxlorenz2018.frac_returns,...
    taxlorenz2018.frac_tax, 'pchip');
% get calculated parameters for annotation
params = readtable('../data/params.csv', 'ReadRowNames', true);
fp = params('2018',:).fp;
ft = params('2018',:).ft;

% settings
markersize = 5;
linewidth = 1.2;
fontsize = 12;
legendbox = 'off';
figure('Position',[350,50,640,580])

%% Lorenz curve
mainaxes = axes(...
    'XLim', [0 1],...
    'XMinorTick', 'on',...
    'YMinorTick', 'on',...
    'YLim', [0 1],...
    'XTick', 0:0.1:1,...
    'YTick', 0:0.1:1,...
    'LabelFontSizeMultiplier', 1,...
    'FontSize', fontsize,...
    'DefaultTextFontSize', fontsize,...
    'Box', 'on');
% set minor ticks to 1%
mainaxes.XAxis.MinorTickValues = 0:0.01:1;
mainaxes.YAxis.MinorTickValues = 0:0.01:1;
% labels
xlabel('Cumulative fraction of returns')
ylabel('Cumulative fraction of tax revenue')
title('Lorenz curves for tax distribution',...
    'FontWeight', 'default',...
    'FontSize', fontsize)
hold on

% equality 45 degree curve (with gap for Gini plot)
plot([0 0.5], [0 0.5], 'k',...
    'LineWidth', linewidth)
plot([0.7 1], [0.7 1], 'k',...
    'LineWidth', linewidth)

% pure exponential fit curve (with gaps for labels)
% use smaller step sizes for X near the top of the distribution in order
% to for it to extend all the way to the top corner
X1 = 0:0.01:0.905;
X2 = [0.93:0.001:0.995, 0.9951:0.0001:0.9999];
plot(X1, X1 + (1-X1) .* log(1-X1), 'k',...
    'LineWidth', linewidth)
plot(X2, X2 + (1-X2) .* log(1-X2), 'k',...
    'LineWidth', linewidth)

% interpolants
X = 0:0.001:1;
plot(X, interp1983(X), 'r-',...
    'LineWidth', linewidth)
plot(X, interp2018(X), 'b-',...
    'LineWidth', linewidth)

% data points
plot(taxlorenz1983.frac_returns, taxlorenz1983.frac_tax, 'rs',...
    'MarkerFaceColor', 'r',...
    'MarkerSize', markersize*1.1)
plot(taxlorenz2018.frac_returns, taxlorenz2018.frac_tax, 'bo',...
    'MarkerFaceColor', 'b',...
    'MarkerSize', markersize)

% plot fp and ft point
plot(1-fp, 1-ft, 'md',...
    'MarkerFaceColor', 'm',...
    'MarkerSize', markersize*1.2)

% fp and ft annotations
plot([1-fp 1-fp],[1-ft 1], 'm:',...
    'LineWidth', linewidth)
text(0.818,0.71,...
    '$$f_t$$',...
    'Color', 'm',...
    'Interpreter', 'latex',...
    'FontSize', 1.2*fontsize)
text(0.845,0.713,...
    ' = 58%',...
    'Color', 'm',...
    'FontWeight', 'default')

plot([1-fp 1],[1-ft 1-ft], 'm:',...
    'LineWidth', linewidth)
text(0.879,0.217,...
    '$$f_p$$',...
    'Color', 'm',...
    'Interpreter', 'latex',...
    'FontSize', 1.2*fontsize)
text(0.908,0.223,...
    ' = 4%',...
    'Color', 'm',...
    'FontWeight', 'default')

% Lorenz labels and arrows
annotation('arrow', [0.528,0.528], [0.326,0.265],...
    'Color', 'k',...
    'LineWidth', linewidth)
annotation('arrow', [0.89,0.89], [0.32,0.44],...
    'Color', 'm',...
    'LineWidth', linewidth)
text(0.676,0.289, '\color{red}1983')
text(0.774,0.11, '\color{blue}2018')
text(0.427,0.331, 'Exponential')
text(0.434,0.296, 'distribution')

%% inset Gini plot
insetaxes = axes(....
    'Position', [0.2 0.55 0.45 0.35], ...
    'XLim', [1981 2019],...
    'YLim', [0 1],...
    'XTick', 1985:5:2015,...
    'XTickLabel', [],...
    'XMinorTick', 'on',...
    'Box', 'on',...
    'LabelFontSizeMultiplier', 1,...
    'FontSize', fontsize,...
    'DefaultTextFontSize', fontsize);
% manually do xticklabels for gini inset so they go inside the plot
for year = 1985:5:2015
   text(year-1.5, 0.07, string(year),...
       'Rotation', 45,...
       'Color', [0.15 0.15 0.15])
end
hold on

% gini = 0.5
plot([1981 2020], [0.5 0.5], 'k', ...
    'LineWidth', linewidth)

% data points
plot(1983:2018, params.taxgini,'bo',...
    'MarkerSize', markersize,...
    'LineWidth', linewidth)

% inset legend
text(1991.5, 0.91,...
    'Tax Gini coefficient',...
    'FontSize', fontsize)
    
%% saving figure so that it isn't just 8.5" x 11"
% get the Position in inches, not pixels
set(gcf, 'Units', 'Inches');
figpos = get(gcf, 'Position');
% PaperSize is automatically [8.5, 11]
set(gcf, 'PaperSize', figpos(3:4));
saveas(gcf, 'fig7.pdf');



